config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    
    resources :comments, only: [:create, :destroy]
    
    collection do
      # 瀏覽所有餐廳的最近動態
      get :feeds
      
      # TOP 10 餐廳
      get :ranking
    end
    
    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end
    
    # 比較[收藏／取消收藏]、[喜翻／收回喜翻]這兩種不同的寫法
    
    member do
      # 收藏／取消收藏
      post :favorite
      post :unfavorite
      delete :unfavorite2
    end
    
    # 喜翻／收回喜翻
    resources :likes, only: [:create, :destroy]
    # 上面的這個寫法其實就是跟 comment 一樣的東西
    
  end
  resources :categories, only: [:show]
  
  resources :users, only: [:show, :edit, :update, :index]
  
  # 追蹤／取消追蹤
  resources :followships, only: [:create, :destroy]
  
  # 好友邀請／取消邀請
  resources :friendships, only: [:create, :destroy] do
    
    member do
      # 接受好友邀請
      post :accept
      # 拒絕好友邀請
      delete :reject
    end
    
  end
  
  root 'restaurants#index'
  
  namespace :admin, path: "c7edcc" do
    resources :restaurants do
      # 瀏覽所有收藏者
      get :favorites
    end  
    resources :categories
    root 'restaurants#index'
  end
  
  resources :repos
  
end

app/models/repo.rb
# == Schema Information
#
# Table name: repos
#
#  id          :integer          not null, primary key
#  site_name   :string
#  site_url    :string
#  github_name :string
#  github_url  :string
#  account     :string
#  password    :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  sort        :integer
#

class Repo < ApplicationRecord
  
  before_save :initialize_github_name
  
  def initialize_github_name
    if self.github_name == nil || self.github_name == ""
      self.github_name = self.github_url.split("://github.com/").last
    end
  end
    
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  
  def index
    @repos = Repo.all.order(sort: :desc)
  end
  
  def new
    @repo = Repo.new
  end
  
  def create
    @repo = Repo.new(repo_params)
    if @repo.save
      redirect_to repos_path
    else
      render :new
    end
  end
  
  def edit
    @repo = Repo.find(params[:id])
  end
  
  def update
    @repo = Repo.find(params[:id])
    if @repo.update(repo_params)
      redirect_to repos_path
    else
      render :edit
    end
  end
  
  def destroy
    @repo = Repo.find(params[:id])
    @repo.destroy
    redirect_to repos_path
  end
  
  private 
  
  def repo_params
    params.require(:repo).permit(
      :site_name,
      :site_url,
      :github_name,
      :github_url,
      :account,
      :password,
      :description,
      :sort
      )
  end

end

app/helpers/repos_helper.rb
module ReposHelper
end

app/views/repos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
    
    <%= form_for @repo do |f| %>
    
    <div class="form-row"> 
      
      <div class="form-group">
        <%= f.label :site_name, "Site Name" %>
        <%= f.text_field :site_name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :site_url, "Site Url" %>
        <%= f.text_field :site_url, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :github_name, "Github Name" %>
        <%= f.text_field :github_name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :github_url, "Github Url" %>
        <%= f.text_field :github_url, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :account, "Account" %>
        <%= f.text_field :account, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.text_field :password, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :description, "Description" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :sort, "Sort" %>
        <%= f.text_field :sort, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
      
    <% end %>
    
    </div>
    
    </div>
  </div>
</div>

app/views/repos/index.html.erb
<%= link_to new_repo_path do %>
新增資料
<% end %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">Site Name</th>
            <th scope="col">GitHub</th>
            <th scope="col">Admin</th>
            <th scope="col">Password</th>
            <th scope="col">Description</th>
            <th scope="col">Description</th>
          </tr>
        </thead>
        <tbody>
          <% @repos.each do |repo| %>
          <tr>
            <td class="col-md-3">
              <a href="<%= repo.site_url %>" target="_blank"><%= repo.site_name %></a>
            </td>
            <td class="col-md-3">
              <a href="<%= repo.github_url %>" target="_blank"><%= repo.github_name %></a>
            </td>  
            <td class="col-md-1"><%= repo.account %></td>
            <td class="col-md-1"><%= repo.password %></td>
            <td class="col-md-3"><%= repo.description %></td>
            <td class="col-md-2">
              <%= link_to "Edit", edit_repo_path(repo.id) %>
              <%= link_to "Delete", repo_path(repo.id), method: :delete %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/repos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
    
    <%= form_for @repo do |f| %>
    
    <div class="form-row"> 
      
      <div class="form-group">
        <%= f.label :site_name, "Site Name" %>
        <%= f.text_field :site_name, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :site_url, "Site Url" %>
        <%= f.text_field :site_url, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :github_url, "Github Url" %>
        <%= f.text_field :github_url, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :account, "Account" %>
        <%= f.text_field :account, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :password, "Password" %>
        <%= f.text_field :password, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :description, "Description" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.label :sort, "Sort" %>
        <%= f.text_field :sort, class: "form-control" %>
      </div>
      
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
      
    <% end %>
    
    </div>
    
    </div>
  </div>
</div>