config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    
    resources :comments, only: [:create, :destroy]
    
    collection do
      # 瀏覽所有餐廳的最近動態
      get :feeds
      
      # TOP 10 餐廳
      get :ranking
    end
    
    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end
    
    # 比較[收藏／取消收藏]、[喜翻／收回喜翻]這兩種不同的寫法
    
    member do
      # 收藏／取消收藏
      post :favorite
      post :unfavorite
      delete :unfavorite2
    end
    
    # 喜翻／收回喜翻
    resources :likes, only: [:create, :destroy]
    # 上面的這個寫法其實就是跟 comment 一樣的東西
    
  end
  resources :categories, only: [:show]
  
  resources :users, only: [:show, :edit, :update, :index]
  
  # 追蹤／取消追蹤
  resources :followships, only: [:create, :destroy]
  
  # 好友邀請／取消邀請
  resources :friendships, only: [:create, :destroy] do
    
    member do
      # 接受好友邀請
      post :accept
      # 拒絕好友邀請
      delete :reject
    end
    
  end
  
  root 'restaurants#index'
  
  namespace :admin, path: "c7edcc" do
    resources :restaurants do
      # 瀏覽所有收藏者
      get :favorites
    end  
    resources :categories
    root 'restaurants#index'
  end
  
  resources :repos
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  role                   :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  intro                  :text
#  avatar                 :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :comments
  has_many :restaurants, through: :comments
  
  mount_uploader :avatar, AvatarUploader
  
  # 使用者有很多收藏的餐廳的多對多關聯
  has_many :favorites, dependent: :destroy # 當 User 物件被刪件，相關的 Favorite 物件會一併刪除
  has_many :favorited_restaurants, through: :favorites, source: :restaurant
  
  # 使用者有很多喜翻的餐廳的多對多關聯
  has_many :likes, dependent: :destroy # 當 User 物件被刪件，相關的 Favorite 物件會一併刪除
  has_many :liked_restaurants, through: :likes, source: :restaurant
  
  # 使用者有很多追蹝記錄，也有很多他自己正在追蹤的人
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships
  
  # 使用者有很多追蹤自己的人
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user
  
  # 交友邀請相關功能
  has_many :friendships
  has_many :friends, through: :friendships
  
  # 對我發出好友邀請的人
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :want2yous, through: :inverse_friendships, source: :user
  
  
  before_save :initialize_name
  
  def admin?
    self.role == 'admin'
  end
  
  def following?(user)
    self.followings.include?(user)
  end
  
  def friend?(user)
    self.friends.include?(user) & self.want2yous.include?(user)
  end
  
  def request_friend?(user)
    self.friends.include?(user)
  end
  
  def want_to_you?(user)
    self.want2yous.include?(user)
  end
  
  def initialize_name
    if self.name == '' || self.name == nil
      self.name = self.email.split('@').first
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers
    
    # 送出好友邀請，想要他成為好友
    @wanted_friends = @user.friends - @user.want2yous
    
    # 想要你的人
    @want2yous = @user.want2yous - @user.friends
    
    # 互相為好友的人
    @befrinds = @user.want2yous & @user.friends
  end
  
  def edit
    @user = User.find(params[:id])
    
    unless @user.name 
      @user.name = @user.email.split('@').first
    end
    
    unless @user.id == current_user.id
      flash[:notice] = "你沒有權限";
      redirect_to user_path(@user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "user was successfully updated"
    else
      render :edit
      flash[:alert] = "user was failed to update"
    end
  end
  
  private
  
  def user_params
    params.
      require(:user).
      permit(:name, 
        :intro, 
        :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9">

    <% if @user.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %>

    <%= form_for @user do |f| %>
    <div class="form-row">  


      <div class="form-group">
        <%= f.label :name, "Name" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :intro, "Intro" %>
        <%= f.text_area :intro, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :avatar, "Avatar" %>
        <%= image_tag @user.avatar, width: '300px' if @user.avatar? %>
        <%= f.file_field :avatar %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
      </div>
    <% end %>
    </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
  
    <ul class="nav nav-tabs">
      <li>
        <%= link_to '首頁', root_path %>
      </li>
      <li>
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
      <li class="active">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
    
    <br />
    
    <%= render partial: "shared/follow", locals: {users: @users} %> 
    
  </div>  
</div>

app/views/users/show.html.erb
<br />
<div class="container">
  <div class="row">
   
    <div class="col-md-4">      
      <% if @user.avatar? %>
        <%= image_tag @user.avatar, class: "img-responsive center-block img-rounded avatar" %>
      <% else %>
      
        <% x =  rand(2) %>
        <% if x == 0 %>
          <%= image_tag "https://i.imgur.com/vdaV4wT.png", class: "img-responsive center-block img-rounded avatar"  %>
        <% else %>
          <%= image_tag "https://i.imgur.com/UEh3HOm.png", class: "img-responsive center-block img-rounded avatar"  %>
        <% end %>  
      <% end %>       
    </div>
    
    <div class="col-md-8">
      <div class="form-row">  
        <div class="form-group">
          <h2><%= @user.name %></h2>
          <!-- inline & unstyled 的 list -->
          <ul class="list-unstyled list-inline">
           <li><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</li>
           <li><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</li>
           <li><strong><%= @followings.count %></strong> followings</li>
           <li><strong><%= @followers.count %></strong> followers</li>
          </ul>
          <h4><%= @user.intro %></h4>
          <% if @user.id == current_user.id %>
            <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %>
          <% end %>
          
          <% if current_user.friend?(@user) %>
            <%= link_to '取消好友關係', friendship_path(@user), method: :delete, class: "btn btn-danger" %>
          <% elsif current_user.want_to_you?(@user) %>  
            <%= link_to '拒絕好友邀請', reject_friendship_path(@user), method: :delete, class: "btn btn-warning" %>
            <%= link_to '接受好友邀請', accept_friendship_path(@user), method: :post, class: "btn btn-success" %>
          <% elsif current_user.request_friend?(@user) %>
            <%= link_to '取消邀請', friendship_path(@user), method: :delete, class: "btn btn-danger" %>
          <% end %>
          
        </div>
      </div>
    </div>
    
  </div>
</div>


<br>



<div class="col-md-4">
  <!-- 顯示followings的清單，panel包一個list-group  -->
  <div class="panel panel-warning">
   
    <div class="panel-heading">
      <h3 class="panel-title"><strong><%= @followings.count %></strong> followings</h3>
    </div>
    
    <ul class="list-group">
      <% @followings.each do |following| %>
      <li class="list-group-item">
        <%= link_to user_path(following) do %>
        
          <% if following.avatar? %>
            <%= image_tag(following.avatar, height: 30, width: 30, class: "img-circle") %>
          <% else %>
            <% x =  rand(2) %>
            <% if x == 0 %>
              <%= image_tag "https://i.imgur.com/vdaV4wT.png", height: 30, width: 30, class: "img-circle" %>
            <% else %>
              <%= image_tag "https://i.imgur.com/UEh3HOm.png", height: 30, width: 30, class: "img-circle" %>
            <% end %>  
          <% end %> 

          <% if following.name? %>
            <%= following.name %>
          <% else %>
            <%= following.email.split("@").first %>
          <% end %> 
        
        <% end %>
      </li>
      <% end %>
    </ul>
    
  </div>
  
  <!-- 顯示followers的清單，panel包一個list-group  -->
  <div class="panel panel-warning">
   
    <div class="panel-heading">
      <h3 class="panel-title"><strong><%= @followers.count %></strong> followers</h3>
    </div>
    
    <ul class="list-group">
      <% @followers.each do |follower| %>
      <li class="list-group-item">
        <%= link_to user_path(follower) do %>
        
          <% if follower.avatar? %>
            <%= image_tag(follower.avatar, height: 30, width: 30, class: "img-circle") %>
          <% else %>
            <% x =  rand(2) %>
            <% if x == 0 %>
              <%= image_tag "https://i.imgur.com/vdaV4wT.png", height: 30, width: 30, class: "img-circle" %>
            <% else %>
              <%= image_tag "https://i.imgur.com/UEh3HOm.png", height: 30, width: 30, class: "img-circle" %>
            <% end %>  
          <% end %>  
          
          <% if follower.name? %>
            <%= follower.name %>
          <% else %>
            <%= follower.email.split("@").first %>
          <% end %>
        
        <% end %>
      </li>
      <% end %>
    </ul>
    
  </div>
  
  
  
  <!-- 只有自己才能看見自己的好友以及送出好友邀請給誰 -->
  <% if @user.id == current_user.id %>
  
  <!-- 顯示互為好友的清單，panel包一個list-group  -->    
  <div class="panel panel-warning">
   
    <div class="panel-heading">
      <h3 class="panel-title">你有 <strong><%= @befrinds.count %></strong> 個好友</h3>
    </div>
    
    <ul class="list-group">
      <% @befrinds.each do |befrind| %>
      <li class="list-group-item">
        <%= link_to user_path(befrind) do %>
        
          <% if befrind.avatar? %>
            <%= image_tag(befrind.avatar, height: 30, width: 30, class: "img-circle") %>
          <% else %>
            <% x =  rand(2) %>
            <% if x == 0 %>
              <%= image_tag "https://i.imgur.com/vdaV4wT.png", height: 30, width: 30, class: "img-circle" %>
            <% else %>
              <%= image_tag "https://i.imgur.com/UEh3HOm.png", height: 30, width: 30, class: "img-circle" %>
            <% end %>  
          <% end %>  
          
          <% if befrind.name? %>
            <%= befrind.name %>
          <% else %>
            <%= befrind.email.split("@").first %>
          <% end %>
        
        <% end %>
      </li>
      <% end %>
    </ul>
    
  </div> 
  
  <!-- 顯示送出好友邀請的清單，panel包一個list-group  -->  
  <div class="panel panel-warning">
   
    <div class="panel-heading">
      <h3 class="panel-title">你送出了 <strong><%= @wanted_friends.count %></strong> 個好友邀請</h3>
    </div>
    
    <ul class="list-group">
      <% @wanted_friends.each do |wanted_friend| %>
      <li class="list-group-item">
        <%= link_to user_path(wanted_friend) do %>
        
          <% if wanted_friend.avatar? %>
            <%= image_tag(wanted_friend.avatar, height: 30, width: 30, class: "img-circle") %>
          <% else %>
            <% x =  rand(2) %>
            <% if x == 0 %>
              <%= image_tag "https://i.imgur.com/vdaV4wT.png", height: 30, width: 30, class: "img-circle" %>
            <% else %>
              <%= image_tag "https://i.imgur.com/UEh3HOm.png", height: 30, width: 30, class: "img-circle" %>
            <% end %>  
          <% end %>  
          
          <% if wanted_friend.name? %>
            <%= wanted_friend.name %>
          <% else %>
            <%= wanted_friend.email.split("@").first %>
          <% end %>
        
        <% end %>
      </li>
      <% end %>
    </ul>
    
  </div> 
  
  <!-- 對你發出好友邀請的清單，panel包一個list-group  -->  
  <div class="panel panel-warning">
   
    <div class="panel-heading">
      <h3 class="panel-title">有 <strong><%= @want2yous.count %></strong> 個好友邀請</h3>
    </div>
    
    <ul class="list-group">
      <% @want2yous.each do |want2you| %>
      <li class="list-group-item">
        <%= link_to user_path(want2you) do %>
        
          <% if want2you.avatar? %>
            <%= image_tag(want2you.avatar, height: 30, width: 30, class: "img-circle") %>
          <% else %>
            <% x =  rand(2) %>
            <% if x == 0 %>
              <%= image_tag "https://i.imgur.com/vdaV4wT.png", height: 30, width: 30, class: "img-circle" %>
            <% else %>
              <%= image_tag "https://i.imgur.com/UEh3HOm.png", height: 30, width: 30, class: "img-circle" %>
            <% end %>  
          <% end %>  
          
          <% if want2you.name? %>
            <%= want2you.name %>
          <% else %>
            <%= want2you.email.split("@").first %>
          <% end %>
        
        <% end %>
      </li>
      <% end %>
    </ul>
    
  </div>
  <% end %>
  
</div>

<div class="col-md-8">
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h4 class="panel-title">
        評論過的餐廳
      </h4>
    </div>
    <div class="panel-body">
      <% @commented_restaurants.each do |restaurant| %>      
        <%= link_to restaurant_path(restaurant.id) do %>
        <div class="my-restaurant">     
          <% if restaurant.image? %>
            <div>
              <%= image_tag restaurant.image %>
            </div>
          <% else %>
            <%= image_tag "http://via.placeholder.com/100x80" %>
          <% end %>   
          <p><%= restaurant.name %></p>
          <br />
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>