config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    
    resources :comments, only: [:create, :destroy]
    
    collection do
      # 瀏覽所有餐廳的最近動態
      get :feeds
      
      # TOP 10 餐廳
      get :ranking
    end
    
    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end
    
    # 比較[收藏／取消收藏]、[喜翻／收回喜翻]這兩種不同的寫法
    
    member do
      # 收藏／取消收藏
      post :favorite
      post :unfavorite
      delete :unfavorite2
    end
    
    # 喜翻／收回喜翻
    resources :likes, only: [:create, :destroy]
    # 上面的這個寫法其實就是跟 comment 一樣的東西
    
  end
  resources :categories, only: [:show]
  
  resources :users, only: [:show, :edit, :update, :index]
  
  # 追蹤／取消追蹤
  resources :followships, only: [:create, :destroy]
  
  # 好友邀請／取消邀請
  resources :friendships, only: [:create, :destroy] do
    
    member do
      # 接受好友邀請
      post :accept
      # 拒絕好友邀請
      delete :reject
    end
    
  end
  
  root 'restaurants#index'
  
  namespace :admin, path: "c7edcc" do
    resources :restaurants do
      # 瀏覽所有收藏者
      get :favorites
    end  
    resources :categories
    root 'restaurants#index'
  end
  
  resources :repos
  
end

app/views/shared/_alert.html.erb
<% if flash[:alert] %>
<div class="container">
  <div class="row">
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= alert %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
 <%= link_to "取消收藏1", unfavorite_restaurant_path(restaurant), class: "btn btn-info", method: :post, data: { confirm: "確定不要人家了喔 T_T?" } %>
  <%= link_to "取消收藏", unfavorite2_restaurant_path(restaurant), class: "btn btn-info", method: :delete, data: { confirm: "確定不要人家了喔 T_T?"} %>
<% else %>
  <%= link_to "收藏", favorite_restaurant_path(restaurant), class: "btn btn-info", method: :post, data: { disable_with: "Waiting...."} %>
<% end %>

app/views/shared/_follow.html.erb
<% users.each do |user| %>
  <% if user != current_user %>
    <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
      <%= link_to user_path(user) do %>
        <!-- 可先利用 Placeholder 如 <img src="http://via.placeholder.com/128x128"> 產生圖片 -->
       <!-- <img src="http://via.placeholder.com/128x128">-->
         
      <% if user.avatar? %>
        <%= image_tag(user.avatar, class: "img-rounded") %>
      <% else %>
      
        <% x =  rand(2) %>
        <% if x == 0 %>
          <%= image_tag "https://i.imgur.com/vdaV4wT.png", class: "img-rounded"  %>
        <% else %>
          <%= image_tag "https://i.imgur.com/UEh3HOm.png", class: "img-rounded"  %>
        <% end %>  
      <% end %>   
        
        
      <h4>
        <% if !user.name %>
          <%=  user.name = user.email.split('@').first %>
        <% else %>
          <%= user.name %>
        <% end %>
      </h4>
      
      <% end %>
      
      
      <% if current_user.following?(user) %>
        <%= link_to '取消追蹤', followship_path(user), method: :delete, class: "btn btn-danger" %>
      <% else %>
        <!-- 會用 POST 動作導向 http://localhost:3000/followships?following_id={user.id} -->
        <%= link_to '追蹤', followships_path(following_id: user), method: :post,class: "btn btn-primary" %>
      <% end %>
      
      <% if current_user.friend?(user) %>
        <%= link_to '解除好友關係', friendship_path(user), method: :delete, class: "btn btn-danger" %>
      <% elsif current_user.request_friend?(user) %>
        <%= link_to '交友邀請已送出', friendship_path(user), method: :delete, class: "btn btn-success" %>
      <% else %>  
        <%= link_to '加朋友', friendships_path(friend_id: user), method: :post,class: "btn btn-primary" %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<ul class="nav nav-pills nav-pills-center">
  <li class="<%= "active" if @category == nil %>"><%= link_to "全部餐廳", root_path %></li>
  <% @categories.each do |category| %>
    <li class="<%= "active" if category == @category %>"><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

app/views/shared/_navbar.html.erb
<!-- 導覽列 --> 
<nav class="navbar navbar-<%= look %>">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "玲玲的美食", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="pull-right text-right nav navbar-nav">
        <% if current_user %>
          <!-- start of 新增 Admin 後台 -->
          <% if current_user.admin? %>
            <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
          <% end %>
          <!-- end of 新增 Admin 後台 -->
          <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
          <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
        <% else %>
          <li><%= link_to('註冊', new_user_registration_path) %></li>
          <li><%= link_to('登入', new_user_session_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 

app/views/shared/_navbar_admin.html.erb
<!-- 導覽列 -->
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "玲玲的美食", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="pull-right text-right nav navbar-nav">
        <% if current_user %>
          <!-- start of 新增 Admin 後台 -->
          <% if current_user.admin? %>
            <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
          <% end %>
          <!-- end of 新增 Admin 後台 -->
          <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
          <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
          <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
        <% else %>
          <li><%= link_to('註冊', new_user_registration_path) %></li>
          <li><%= link_to('登入', new_user_session_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 

app/views/shared/_navbar_user.html.erb
<!-- 導覽列 -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "玲玲的美食", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="pull-right text-right nav navbar-nav">
        <% if current_user %>
          <!-- start of 新增 Admin 後台 -->
          <% if current_user.admin? %>
            <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
          <% end %>
          <!-- end of 新增 Admin 後台 -->
          <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
          <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
          <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
        <% else %>
          <li><%= link_to('註冊', new_user_registration_path) %></li>
          <li><%= link_to('登入', new_user_session_path) %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav> 

app/views/shared/_notice.html.erb
<% if flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="alert alert-success alert-dismissible" role="alert">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
     </button>
      <%= notice %>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">
     
      <% if restaurant.image? %>
        <%= image_tag restaurant.image, class: "img-responsive center-block" %>
      <% else %>
      
        <% x =  rand(6) %>
        <% if x == 0 %>
          <%= image_tag "https://i.imgur.com/eZtNIiR.jpg", class: "img-responsive center-block img-rounded"  %>
        <% elsif x == 1 %>
          <%= image_tag "https://i.imgur.com/0gE7uAS.jpg", class: "img-responsive center-block img-rounded"  %>
        <% elsif x == 2 %>
          <%= image_tag "https://i.imgur.com/eNBWOa8.jpg", class: "img-responsive center-block img-rounded"  %>
        <% elsif x == 3 %>
          <%= image_tag "https://i.imgur.com/WzQrFB2.jpg", class: "img-responsive center-block img-rounded"  %>
        <% elsif x == 4 %>
          <%= image_tag "https://i.imgur.com/0tjHOrG.jpg", class: "img-responsive center-block img-rounded"  %> 
        <% else%>
          <%= image_tag "https://i.imgur.com/bJSckSZ.jpg", class: "img-responsive center-block img-rounded"  %>
        <% end %>
        
      <!--
       image_tag "http://via.placeholder.com/338x180", class: "img-responsive center-block img-rounded" %>
      -->
      <% end %>
      <div class="caption">
        <h3><%= link_to restaurant.name, restaurant_path(restaurant.id) %> </h3>
        <span class="label label-success"><%= restaurant.category.name %></span>
        <span class="label label-default">
          <% (1 + rand(5)).times do %>
            <span class="glyphicon glyphicon-star" style="color: yellow"></span>
          <% end %>
        </span>
        <p><%= truncate(restaurant.description, length: 80) %></p>
        <span><%= render partial: "shared/favorite", locals: {restaurant: restaurant} %></span> 
        
        <span>
        <% if restaurant.is_liked?(current_user) %>
          <%= link_to "收回喜翻", restaurant_like_path(restaurant, current_user.liked_restaurants.first.id), class: "btn btn-danger", method: :delete, data: { confirm: "確定對這家餐廳森77?"}  %>
        <% else %>
          <%= link_to "喜翻", restaurant_likes_path(restaurant), class: "btn btn-danger", method: :post %>
        <% end %>
        </span>
        
      </div>
    </div>
  </div>
<% end %>

<!-- 有generate kaminari paginate bootstrap style -->
<div class="text-center">
  <%= paginate @restaurants %>
</div>

app/views/shared/_sidebar.html.erb
<div class="panel-group">
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h4 class="panel-title">
        功能管理
      </h4>
    </div>
    <div class="panel-body">
      <ul>              
        <li><%= link_to 'Restaurant', admin_restaurants_path %></li>
        <li><%= link_to 'Categories', admin_categories_path %></li>
      </ul>    
    </div>
  </div>
</div>


<div class="panel-group">
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h4 class="panel-title">
        好站推薦
      </h4>
    </div>
    <div class="panel-body">
      <ul>              
        <li><a href="https://fast-plains-25699.herokuapp.com/" target="_blank">小可愛的餐廳</a></li>
        <li><a href="https://restaurant-forum-by-yipee.herokuapp.com/" target="_blank">好好吃餐廳</a></li>
        <li><a href="https://restaurant-forum-ac.herokuapp.com/" target="_blank">豪大間餐廳</a></li>
      </ul>
      <p>帳號：root@example.com </p>
      <p>密碼：12345678</p>
    </div>
  </div>
</div>