config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :restaurants, only: [:index, :show] do
    
    resources :comments, only: [:create, :destroy]
    
    collection do
      # 瀏覽所有餐廳的最近動態
      get :feeds
      
      # TOP 10 餐廳
      get :ranking
    end
    
    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end
    
    # 比較[收藏／取消收藏]、[喜翻／收回喜翻]這兩種不同的寫法
    
    member do
      # 收藏／取消收藏
      post :favorite
      post :unfavorite
      delete :unfavorite2
    end
    
    # 喜翻／收回喜翻
    resources :likes, only: [:create, :destroy]
    # 上面的這個寫法其實就是跟 comment 一樣的東西
    
  end
  resources :categories, only: [:show]
  
  resources :users, only: [:show, :edit, :update, :index]
  
  # 追蹤／取消追蹤
  resources :followships, only: [:create, :destroy]
  
  # 好友邀請／取消邀請
  resources :friendships, only: [:create, :destroy] do
    
    member do
      # 接受好友邀請
      post :accept
      # 拒絕好友邀請
      delete :reject
    end
    
  end
  
  root 'restaurants#index'
  
  namespace :admin, path: "c7edcc" do
    resources :restaurants do
      # 瀏覽所有收藏者
      get :favorites
    end  
    resources :categories
    root 'restaurants#index'
  end
  
  resources :repos
  
end

app/models/restaurant.rb
# == Schema Information
#
# Table name: restaurants
#
#  id              :integer          not null, primary key
#  name            :string
#  tel             :string
#  address         :string
#  opening_hours   :string
#  description     :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  image           :string
#  category_id     :integer
#  favorites_count :integer          default(0)
#

class Restaurant < ApplicationRecord
  
  is_impressionable
  
  validates :name, presence: true
  # validates_presence_of :name
    
  mount_uploader :image, PhotoUploader
  
  belongs_to :category, optional: true # 允許外鍵 nil
  
  has_many :comments, dependent: :destroy
  
  # 餐廳有很多使用者來收藏它
  has_many :favorites, dependent: :destroy # :destroy 當 User 物件被刪除時，相關的 Favorite 物件會一併被刪除
  has_many :favorited_users, through: :favorites, source: :user
   
  # 餐廳有很多使用者喜翻
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  default_scope { order(created_at: :desc) }
  
  def is_favorited?(user)
    self.favorited_users.include?(user)
  end
  
  def is_liked?(user)
    self.liked_users.include?(user)
  end
  
  def count_favorites
    self.favorites_count = self.favorites.size
    self.save
  end
    
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(8)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path
      flash[:notice] = "restaurant was successfully updated"
    else
      render :edit
      flash[:alert] = "restaurant was failed to update"
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was delete"
  end
  
  def favorites
    @restaurant = Restaurant.find(params[:restaurant_id])
    @favorites = @restaurant.favorites
  end
  
  private
  
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  
  def restaurant_params
    params.
      require(:restaurant).
      permit(:name, 
        :opening_hours, 
        :tel,
        :address,
        :description,
        :image,
        :category_id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  impressionist :actions => [:show]

  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end
  
  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
    impressionist(@restaurant, "message...") # 2nd argument is optional
  end
  
  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end
  
  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end
  
  # POST /restaurants/:id/favorite(.:format)
  def favorite
    restaurant = Restaurant.find(params[:id])
    restaurant.favorites.create!(user: current_user)
    restaurant.count_favorites
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end
  
  def unfavorite
    restaurant = Restaurant.find(params[:id])
    favorite = Favorite.find_by("restaurant_id" => restaurant.id, "user_id" => current_user.id)
    restaurant.count_favorites
    favorite.destroy
    
    # 下面這樣寫法也是可以的
    # favorite = Favorite.where(restaurant: @restaurant, user: current_user)
    # favorite.destroy_all
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end
  
  def unfavorite2
    restaurant = Restaurant.find(params[:id])
    favorite = Favorite.find_by("restaurant_id" => restaurant.id, "user_id" => current_user.id)
    restaurant.count_favorites
    favorite.destroy
    
    # 下面這樣寫法也是可以的
    # favorite = Favorite.where(restaurant: @restaurant, user: current_user)
    # favorite.destroy_all
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end
  
  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end  
  
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.html.erb
<h1><%= @restaurant.name %>'s Dashboard</h1>
<hr>
<ul>
  <li>有 <%= @restaurant.comments.count %> 筆評論</li>
  <li>這家餐廳的平均價位為 $XXX</li>
  <li>有 XX 人收藏這家餐廳</li>
</ul>

app/views/restaurants/favorites.html.erb
<div class="container">
  <div class="row">
   <h3>收藏 <%= @restaurant.name %> 的人</h3>
   <br />
    <% @favorites.each do |favorite| %> 
      <div class="col-md-3 col-sm-4 col-xs-6 text-center user-item">
          <!-- 可先利用 Placeholder 如 <img src="http://via.placeholder.com/128x128"> 產生圖片 -->
          <img src="http://via.placeholder.com/128x128">
          <!-- <%= image_tag(favorite.user.avatar, class: "img-rounded") %>-->
        <h4>
          <% if !favorite.user.name %>
            <%=  favorite.user.name = favorite.user.email.split('@').first %>
          <% else %>
            <%= favorite.user.name %>
          <% end %>
        </h4>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/feeds.html.erb
<div class="container">
  <div class="row">
  
    <ul class="nav nav-tabs">
      <li>
        <%= link_to '首頁', root_path %>
      </li>
      <li class="active">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
    
    <br />
    
    <div class="col-md-6">
     
      <div class="panel-group">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">
            最新餐廳
            </h3>
          </div>
          <div class="panel-body">
            <% @recent_restaurants.each do |restaurant| %>
            <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
            <p><%= restaurant.category.name %></p>
            <p><%= restaurant.description %></p>
            <hr>
            <% end %>
          </div>
        </div>
      </div>
    
    </div>
    
    <div class="col-md-6">
      <div class="panel-group">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">
            最新評論
            </h3>
          </div>
          <div class="panel-body">
            <% @recent_comments.each do |comment| %>
            <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %></h4>
            <p><%= comment.content %></p>
            <p>by <%= link_to comment.user.name, user_path(comment.user) %></p>
            <hr>
            <% end %>
          </div>
        </div>
      </div>
    </div>
                    
  </div>  
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
     
    <ul class="nav nav-tabs">
      <li class="active">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>      
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
    
    <br />
   
    <%= render(partial: "shared/nav") %>
    
    <br />
    
     <%= render(partial: "shared/restaurant_list") %>
      
  </div>
</div>

app/views/restaurants/ranking.html.erb
<div class="container">
  <div class="row">
  
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
      <li role="presentation" class="active">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>      
      <li role="presentation">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>
    
    <br />
   
    <div class="col-md-10 col-md-offset-1">
     
      <div class="page-header">
        <h1>Top 10 人氣餐廳 <small>(收藏數最高)</small></h1>
      </div>
      
      <% @restaurants.each do |restaurant| %>
       
        <div class="ranking-item">
          <div class="col-md-3">
            <%= link_to restaurant_path(restaurant) do %>
             
              <% if restaurant.image? %>
                <%= image_tag restaurant.image, class: "img-responsive center-block" %>
              <% else %>

                <% x =  rand(6) %>
                <% if x == 0 %>
                  <%= image_tag "https://i.imgur.com/eZtNIiR.jpg", class: "img-responsive center-block img-rounded"  %>
                <% elsif x == 1 %>
                  <%= image_tag "https://i.imgur.com/0gE7uAS.jpg", class: "img-responsive center-block img-rounded"  %>
                <% elsif x == 2 %>
                  <%= image_tag "https://i.imgur.com/eNBWOa8.jpg", class: "img-responsive center-block img-rounded"  %>
                <% elsif x == 3 %>
                  <%= image_tag "https://i.imgur.com/WzQrFB2.jpg", class: "img-responsive center-block img-rounded"  %>
                <% elsif x == 4 %>
                  <%= image_tag "https://i.imgur.com/0tjHOrG.jpg", class: "img-responsive center-block img-rounded"  %> 
                <% else%>
                  <%= image_tag "https://i.imgur.com/bJSckSZ.jpg", class: "img-responsive center-block img-rounded"  %>
                <% end %>

              <!--
               image_tag "http://via.placeholder.com/338x180", class: "img-responsive center-block img-rounded" %>
              -->
              <% end %>
              
            <% end %>
          </div>
          <div class="col-md-9">
            <h4>
              <%= restaurant.name %>
              <span class="label label-default">收藏數：<%= restaurant.favorites_count %></span>
            </h4>
            <p><%= truncate(restaurant.description, length: 200) %></p>
            <div>
              <%= link_to 'Show', restaurant_path(restaurant), class: "btn btn-primary" %>
              <%= render partial: 'shared/favorite', locals: { restaurant: restaurant } %>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>
        
      <% end %>
      
    </div>
      
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>

    <div class="col-md-4">
      <% if @restaurant.image? %>
        <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <% else %>
      
        <% x =  rand(6) %>
        <% if x == 0 %>
          <%= image_tag "https://i.imgur.com/eZtNIiR.jpg", class: "img-responsive center-block img-rounded"  %>
        <% elsif x == 1 %>
          <%= image_tag "https://i.imgur.com/0gE7uAS.jpg", class: "img-responsive center-block img-rounded"  %>
        <% elsif x == 2 %>
          <%= image_tag "https://i.imgur.com/eNBWOa8.jpg", class: "img-responsive center-block img-rounded"  %>
        <% elsif x == 3 %>
          <%= image_tag "https://i.imgur.com/WzQrFB2.jpg", class: "img-responsive center-block img-rounded"  %>
        <% elsif x == 4 %>
          <%= image_tag "https://i.imgur.com/0tjHOrG.jpg", class: "img-responsive center-block img-rounded"  %> 
        <% else%>
          <%= image_tag "https://i.imgur.com/bJSckSZ.jpg", class: "img-responsive center-block img-rounded"  %>
        <% end %>
        
      <!--
       image_tag "http://via.placeholder.com/338x180", class: "img-responsive center-block img-rounded" %>
      -->
      <% end %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
      <hr>
      <%= link_to "Dashboard", dashboard_restaurant_path(@restaurant), class: "btn btn-primary" %>
      
      <%= render partial: "shared/favorite", locals: {restaurant: @restaurant} %>
            
    </div>

    <div class="clearfix"></div>

    <hr>

  </div>
  
  <div class="row">
   
    <div class="col-md-12">
      <!-- 顯示與餐廳相關的評論 -->
      <% @restaurant.comments.each do |comment| %>
      <div>
        <h4><%= comment.user.email.split("@")[0] %></h4>
        <p><%= simple_format comment.content %></p>
        <p class="text-muted">
          <em><%= time_ago_in_words(comment.created_at) %> ago </em>
            <% if current_user.admin? %>
            - <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
            <% end %>
        </p>
      </div>
      <hr>
      <% end %>
    </div>
      
    <div class="col-md-12">
      <!-- 新增評論的表單輸入框 -->
      <%= form_for [@restaurant, @comment] do |f| %>
      <div class="form-group">
        <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
        <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
      </div>
      <% end %>
    </div>  
  </div>
  
</div>